#!/usr/bin/env sh

restart_waybar() {
  pkill -f waybar
  waybar
}

restart_hyprpaper() {
  hyprpaper 2> /dev/null
  hyprctl hyprpaper reload ",~/.config/background-noblur.png"
}

get_walpaper() {
  BACKGROUNDS=$(ls ~/.config/background/ | cut -d ' ' -f 1)
  NUMBERS_OF_BACKGROUNDS=0

  for j in ${BACKGROUNDS}; do
    ((NUMBERS_OF_BACKGROUNDS++))
  done

  WALPAPER=$(
    echo ${BACKGROUNDS} | cut -d ' ' -f $((1 + RANDOM % NUMBERS_OF_BACKGROUNDS))
  )
}

blur_walpaper() {
  convert \
    ~/.config/background/${WALPAPER} \
    -filter Gaussian -blur 0x32 \
    ~/.config/background.png &
}

copy_walpaper() {
  rm ~/.config/background-noblur.png
  ln -s ~/.config/background/${WALPAPER} ~/.config/background-noblur.png &
  restart_hyprpaper &
}

update_wal() {
  wpg -a ~/.config/background/${WALPAPER}
  wpg -A ${WALPAPER}
  wpg -s ${WALPAPER}

  restart_waybar &
  hyprctl reload &
}

main() {
  cpwrconf
  get_walpaper
  blur_walpaper &
  update_wal
  kitty @ set-colors --all ~/.cache/wal/colors-kitty.conf
  copy_walpaper &
}

main > /dev/null 2>&1
